/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SpeedInsightsRouteImport } from './routes/speed-insights'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as FirewallRouteImport } from './routes/firewall'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LogsRouteRouteImport } from './routes/logs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeedInsightsRoute = SpeedInsightsRouteImport.update({
  id: '/speed-insights',
  path: '/speed-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallRoute = FirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRouteRoute = LogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/deployments': typeof DeploymentsRoute
  '/firewall': typeof FirewallRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/speed-insights': typeof SpeedInsightsRoute
  '/support': typeof SupportRoute
  '/usage': typeof UsageRoute
  '/logs/': typeof LogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/deployments': typeof DeploymentsRoute
  '/firewall': typeof FirewallRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/speed-insights': typeof SpeedInsightsRoute
  '/support': typeof SupportRoute
  '/usage': typeof UsageRoute
  '/logs': typeof LogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/deployments': typeof DeploymentsRoute
  '/firewall': typeof FirewallRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/speed-insights': typeof SpeedInsightsRoute
  '/support': typeof SupportRoute
  '/usage': typeof UsageRoute
  '/logs/': typeof LogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/analytics'
    | '/deployments'
    | '/firewall'
    | '/observability'
    | '/settings'
    | '/speed-insights'
    | '/support'
    | '/usage'
    | '/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/deployments'
    | '/firewall'
    | '/observability'
    | '/settings'
    | '/speed-insights'
    | '/support'
    | '/usage'
    | '/logs'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/analytics'
    | '/deployments'
    | '/firewall'
    | '/observability'
    | '/settings'
    | '/speed-insights'
    | '/support'
    | '/usage'
    | '/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRouteRoute: typeof LogsRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  DeploymentsRoute: typeof DeploymentsRoute
  FirewallRoute: typeof FirewallRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
  SpeedInsightsRoute: typeof SpeedInsightsRoute
  SupportRoute: typeof SupportRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speed-insights': {
      id: '/speed-insights'
      path: '/speed-insights'
      fullPath: '/speed-insights'
      preLoaderRoute: typeof SpeedInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewall': {
      id: '/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof FirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof LogsRouteRoute
    }
  }
}

interface LogsRouteRouteChildren {
  LogsIndexRoute: typeof LogsIndexRoute
}

const LogsRouteRouteChildren: LogsRouteRouteChildren = {
  LogsIndexRoute: LogsIndexRoute,
}

const LogsRouteRouteWithChildren = LogsRouteRoute._addFileChildren(
  LogsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRouteRoute: LogsRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  DeploymentsRoute: DeploymentsRoute,
  FirewallRoute: FirewallRoute,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
  SpeedInsightsRoute: SpeedInsightsRoute,
  SupportRoute: SupportRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
